/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */

import * as Logos from '../../bitcoin-color';

export const LOGO_LIST = [
  { logo: Logos.LogoBitcoinColor1, name: 'LogoBitcoinColor1' },
  { logo: Logos.LogoBitcoinColor10, name: 'LogoBitcoinColor10' },
  { logo: Logos.LogoBitcoinColor11, name: 'LogoBitcoinColor11' },
  { logo: Logos.LogoBitcoinColor12, name: 'LogoBitcoinColor12' },
  { logo: Logos.LogoBitcoinColor13, name: 'LogoBitcoinColor13' },
  { logo: Logos.LogoBitcoinColor14, name: 'LogoBitcoinColor14' },
  { logo: Logos.LogoBitcoinColor15, name: 'LogoBitcoinColor15' },
  { logo: Logos.LogoBitcoinColor16, name: 'LogoBitcoinColor16' },
  { logo: Logos.LogoBitcoinColor17, name: 'LogoBitcoinColor17' },
  { logo: Logos.LogoBitcoinColor18, name: 'LogoBitcoinColor18' },
  { logo: Logos.LogoBitcoinColor19, name: 'LogoBitcoinColor19' },
  { logo: Logos.LogoBitcoinColor2, name: 'LogoBitcoinColor2' },
  { logo: Logos.LogoBitcoinColor20, name: 'LogoBitcoinColor20' },
  { logo: Logos.LogoBitcoinColor21, name: 'LogoBitcoinColor21' },
  { logo: Logos.LogoBitcoinColor22, name: 'LogoBitcoinColor22' },
  { logo: Logos.LogoBitcoinColor23, name: 'LogoBitcoinColor23' },
  { logo: Logos.LogoBitcoinColor24, name: 'LogoBitcoinColor24' },
  { logo: Logos.LogoBitcoinColor25, name: 'LogoBitcoinColor25' },
  { logo: Logos.LogoBitcoinColor26, name: 'LogoBitcoinColor26' },
  { logo: Logos.LogoBitcoinColor27, name: 'LogoBitcoinColor27' },
  { logo: Logos.LogoBitcoinColor28, name: 'LogoBitcoinColor28' },
  { logo: Logos.LogoBitcoinColor29, name: 'LogoBitcoinColor29' },
  { logo: Logos.LogoBitcoinColor3, name: 'LogoBitcoinColor3' },
  { logo: Logos.LogoBitcoinColor30, name: 'LogoBitcoinColor30' },
  { logo: Logos.LogoBitcoinColor31, name: 'LogoBitcoinColor31' },
  { logo: Logos.LogoBitcoinColor32, name: 'LogoBitcoinColor32' },
  { logo: Logos.LogoBitcoinColor33, name: 'LogoBitcoinColor33' },
  { logo: Logos.LogoBitcoinColor34, name: 'LogoBitcoinColor34' },
  { logo: Logos.LogoBitcoinColor35, name: 'LogoBitcoinColor35' },
  { logo: Logos.LogoBitcoinColor36, name: 'LogoBitcoinColor36' },
  { logo: Logos.LogoBitcoinColor4, name: 'LogoBitcoinColor4' },
  { logo: Logos.LogoBitcoinColor5, name: 'LogoBitcoinColor5' },
  { logo: Logos.LogoBitcoinColor6, name: 'LogoBitcoinColor6' },
  { logo: Logos.LogoBitcoinColor7, name: 'LogoBitcoinColor7' },
  { logo: Logos.LogoBitcoinColor8, name: 'LogoBitcoinColor8' },
  { logo: Logos.LogoBitcoinColor9, name: 'LogoBitcoinColor9' },
];