/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */

import * as Logos from '../../bitcoin-grey';

export const LOGO_LIST = [
  { logo: Logos.LogoBitcoinGrey1, name: 'LogoBitcoinGrey1' },
  { logo: Logos.LogoBitcoinGrey10, name: 'LogoBitcoinGrey10' },
  { logo: Logos.LogoBitcoinGrey11, name: 'LogoBitcoinGrey11' },
  { logo: Logos.LogoBitcoinGrey12, name: 'LogoBitcoinGrey12' },
  { logo: Logos.LogoBitcoinGrey13, name: 'LogoBitcoinGrey13' },
  { logo: Logos.LogoBitcoinGrey14, name: 'LogoBitcoinGrey14' },
  { logo: Logos.LogoBitcoinGrey15, name: 'LogoBitcoinGrey15' },
  { logo: Logos.LogoBitcoinGrey16, name: 'LogoBitcoinGrey16' },
  { logo: Logos.LogoBitcoinGrey17, name: 'LogoBitcoinGrey17' },
  { logo: Logos.LogoBitcoinGrey18, name: 'LogoBitcoinGrey18' },
  { logo: Logos.LogoBitcoinGrey19, name: 'LogoBitcoinGrey19' },
  { logo: Logos.LogoBitcoinGrey2, name: 'LogoBitcoinGrey2' },
  { logo: Logos.LogoBitcoinGrey20, name: 'LogoBitcoinGrey20' },
  { logo: Logos.LogoBitcoinGrey21, name: 'LogoBitcoinGrey21' },
  { logo: Logos.LogoBitcoinGrey22, name: 'LogoBitcoinGrey22' },
  { logo: Logos.LogoBitcoinGrey23, name: 'LogoBitcoinGrey23' },
  { logo: Logos.LogoBitcoinGrey24, name: 'LogoBitcoinGrey24' },
  { logo: Logos.LogoBitcoinGrey25, name: 'LogoBitcoinGrey25' },
  { logo: Logos.LogoBitcoinGrey26, name: 'LogoBitcoinGrey26' },
  { logo: Logos.LogoBitcoinGrey27, name: 'LogoBitcoinGrey27' },
  { logo: Logos.LogoBitcoinGrey28, name: 'LogoBitcoinGrey28' },
  { logo: Logos.LogoBitcoinGrey29, name: 'LogoBitcoinGrey29' },
  { logo: Logos.LogoBitcoinGrey3, name: 'LogoBitcoinGrey3' },
  { logo: Logos.LogoBitcoinGrey30, name: 'LogoBitcoinGrey30' },
  { logo: Logos.LogoBitcoinGrey31, name: 'LogoBitcoinGrey31' },
  { logo: Logos.LogoBitcoinGrey32, name: 'LogoBitcoinGrey32' },
  { logo: Logos.LogoBitcoinGrey33, name: 'LogoBitcoinGrey33' },
  { logo: Logos.LogoBitcoinGrey34, name: 'LogoBitcoinGrey34' },
  { logo: Logos.LogoBitcoinGrey35, name: 'LogoBitcoinGrey35' },
  { logo: Logos.LogoBitcoinGrey36, name: 'LogoBitcoinGrey36' },
  { logo: Logos.LogoBitcoinGrey4, name: 'LogoBitcoinGrey4' },
  { logo: Logos.LogoBitcoinGrey5, name: 'LogoBitcoinGrey5' },
  { logo: Logos.LogoBitcoinGrey6, name: 'LogoBitcoinGrey6' },
  { logo: Logos.LogoBitcoinGrey7, name: 'LogoBitcoinGrey7' },
  { logo: Logos.LogoBitcoinGrey8, name: 'LogoBitcoinGrey8' },
  { logo: Logos.LogoBitcoinGrey9, name: 'LogoBitcoinGrey9' },
];