/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */

import * as Logos from '../../vintage-color';

export const LOGO_LIST = [
  { logo: Logos.LogoVintageLogo1, name: 'LogoVintageLogo1' },
  { logo: Logos.LogoVintageLogo10, name: 'LogoVintageLogo10' },
  { logo: Logos.LogoVintageLogo11, name: 'LogoVintageLogo11' },
  { logo: Logos.LogoVintageLogo12, name: 'LogoVintageLogo12' },
  { logo: Logos.LogoVintageLogo13, name: 'LogoVintageLogo13' },
  { logo: Logos.LogoVintageLogo14, name: 'LogoVintageLogo14' },
  { logo: Logos.LogoVintageLogo15, name: 'LogoVintageLogo15' },
  { logo: Logos.LogoVintageLogo16, name: 'LogoVintageLogo16' },
  { logo: Logos.LogoVintageLogo2, name: 'LogoVintageLogo2' },
  { logo: Logos.LogoVintageLogo3, name: 'LogoVintageLogo3' },
  { logo: Logos.LogoVintageLogo4, name: 'LogoVintageLogo4' },
  { logo: Logos.LogoVintageLogo5, name: 'LogoVintageLogo5' },
  { logo: Logos.LogoVintageLogo6, name: 'LogoVintageLogo6' },
  { logo: Logos.LogoVintageLogo7, name: 'LogoVintageLogo7' },
  { logo: Logos.LogoVintageLogo8, name: 'LogoVintageLogo8' },
  { logo: Logos.LogoVintageLogo9, name: 'LogoVintageLogo9' },
];