/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
        
import * as Logos from '../../bitcoin-color';

export const LOGOS_LIST = [
  { logo: Logos.BitcoinColor1, name: 'BitcoinColor1' },
  { logo: Logos.BitcoinColor10, name: 'BitcoinColor10' },
  { logo: Logos.BitcoinColor11, name: 'BitcoinColor11' },
  { logo: Logos.BitcoinColor12, name: 'BitcoinColor12' },
  { logo: Logos.BitcoinColor13, name: 'BitcoinColor13' },
  { logo: Logos.BitcoinColor14, name: 'BitcoinColor14' },
  { logo: Logos.BitcoinColor15, name: 'BitcoinColor15' },
  { logo: Logos.BitcoinColor16, name: 'BitcoinColor16' },
  { logo: Logos.BitcoinColor17, name: 'BitcoinColor17' },
  { logo: Logos.BitcoinColor18, name: 'BitcoinColor18' },
  { logo: Logos.BitcoinColor19, name: 'BitcoinColor19' },
  { logo: Logos.BitcoinColor2, name: 'BitcoinColor2' },
  { logo: Logos.BitcoinColor20, name: 'BitcoinColor20' },
  { logo: Logos.BitcoinColor21, name: 'BitcoinColor21' },
  { logo: Logos.BitcoinColor22, name: 'BitcoinColor22' },
  { logo: Logos.BitcoinColor23, name: 'BitcoinColor23' },
  { logo: Logos.BitcoinColor24, name: 'BitcoinColor24' },
  { logo: Logos.BitcoinColor25, name: 'BitcoinColor25' },
  { logo: Logos.BitcoinColor26, name: 'BitcoinColor26' },
  { logo: Logos.BitcoinColor27, name: 'BitcoinColor27' },
  { logo: Logos.BitcoinColor28, name: 'BitcoinColor28' },
  { logo: Logos.BitcoinColor29, name: 'BitcoinColor29' },
  { logo: Logos.BitcoinColor3, name: 'BitcoinColor3' },
  { logo: Logos.BitcoinColor30, name: 'BitcoinColor30' },
  { logo: Logos.BitcoinColor31, name: 'BitcoinColor31' },
  { logo: Logos.BitcoinColor32, name: 'BitcoinColor32' },
  { logo: Logos.BitcoinColor33, name: 'BitcoinColor33' },
  { logo: Logos.BitcoinColor34, name: 'BitcoinColor34' },
  { logo: Logos.BitcoinColor35, name: 'BitcoinColor35' },
  { logo: Logos.BitcoinColor36, name: 'BitcoinColor36' },
  { logo: Logos.BitcoinColor4, name: 'BitcoinColor4' },
  { logo: Logos.BitcoinColor5, name: 'BitcoinColor5' },
  { logo: Logos.BitcoinColor6, name: 'BitcoinColor6' },
  { logo: Logos.BitcoinColor7, name: 'BitcoinColor7' },
  { logo: Logos.BitcoinColor8, name: 'BitcoinColor8' },
  { logo: Logos.BitcoinColor9, name: 'BitcoinColor9' },
];
