/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */

export { default as LogoVintageLogo1 }
      from './vintage-color/VintageLogo1';
export { default as LogoVintageLogo10 }
      from './vintage-color/VintageLogo10';
export { default as LogoVintageLogo11 }
      from './vintage-color/VintageLogo11';
export { default as LogoVintageLogo12 }
      from './vintage-color/VintageLogo12';
export { default as LogoVintageLogo13 }
      from './vintage-color/VintageLogo13';
export { default as LogoVintageLogo14 }
      from './vintage-color/VintageLogo14';
export { default as LogoVintageLogo15 }
      from './vintage-color/VintageLogo15';
export { default as LogoVintageLogo16 }
      from './vintage-color/VintageLogo16';
export { default as LogoVintageLogo2 }
      from './vintage-color/VintageLogo2';
export { default as LogoVintageLogo3 }
      from './vintage-color/VintageLogo3';
export { default as LogoVintageLogo4 }
      from './vintage-color/VintageLogo4';
export { default as LogoVintageLogo5 }
      from './vintage-color/VintageLogo5';
export { default as LogoVintageLogo6 }
      from './vintage-color/VintageLogo6';
export { default as LogoVintageLogo7 }
      from './vintage-color/VintageLogo7';
export { default as LogoVintageLogo8 }
      from './vintage-color/VintageLogo8';
export { default as LogoVintageLogo9 }
      from './vintage-color/VintageLogo9';
