# Generated by scripts/generate-script.js
# DO NO EDIT

svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/bitcoin-color --ext tsx assets/bitcoin-color
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/misc-color --ext tsx assets/misc-color
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/vintage-color --ext tsx assets/vintage-color
