const fs = require('fs');
const storyTemplate = require('./story-template');

const generate = () => {
  const logoDir = './assets/';
  const saveDir = './src/__stories__/';
  let logoListOutput = '';
  let level1FileName = '';

  // Read root Logo directory
  fs.readdirSync(logoDir).forEach(fileName => {
    if (fileName === '.DS_Store') return;

    const level1Dir = `${logoDir}${fileName}`;

    logoListOutput = `/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
        
import * as Logos from '../${fileName}';

export const LOGO_LIST = [
`;
    // Read level1-directory
    fs.readdirSync(level1Dir).forEach(_level1FileName => {
      if (_level1FileName === '.DS_Store') return;

      level1FileName = _level1FileName;
      
      logoListOutput += `  { logo: Logos.${level1FileName.split('.')[0]}, name: '${level1FileName.split('.')[0]}' },
`;
    });
    logoListOutput += `];
`;
    const categoryName = fileName.split('-').map(str => str[0].toUpperCase() + str.slice(1)).join('');
    const story = storyTemplate(categoryName, fileName);
    fs.writeFileSync(`${saveDir}/${fileName}.ts`, logoListOutput);
    fs.writeFileSync(`${saveDir}/${fileName}.story.tsx`, story);
  });
};

generate();
