/**
 * Generated by scripts/generate-logos.js
 * DO NOT EDIT!
 */

import * as Logos from '../vintage-color';

export const LOGO_LIST = [
  { logo: Logos.VintageColor1, name: 'VintageColor1' },
  { logo: Logos.VintageColor10, name: 'VintageColor10' },
  { logo: Logos.VintageColor11, name: 'VintageColor11' },
  { logo: Logos.VintageColor12, name: 'VintageColor12' },
  { logo: Logos.VintageColor13, name: 'VintageColor13' },
  { logo: Logos.VintageColor14, name: 'VintageColor14' },
  { logo: Logos.VintageColor15, name: 'VintageColor15' },
  { logo: Logos.VintageColor16, name: 'VintageColor16' },
  { logo: Logos.VintageColor2, name: 'VintageColor2' },
  { logo: Logos.VintageColor3, name: 'VintageColor3' },
  { logo: Logos.VintageColor4, name: 'VintageColor4' },
  { logo: Logos.VintageColor5, name: 'VintageColor5' },
  { logo: Logos.VintageColor6, name: 'VintageColor6' },
  { logo: Logos.VintageColor7, name: 'VintageColor7' },
  { logo: Logos.VintageColor8, name: 'VintageColor8' },
  { logo: Logos.VintageColor9, name: 'VintageColor9' },
];
