/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
        
import * as Logos from '../../misc-color';

export const LOGO_LIST = [
  { logo: Logos.MiscColor1, name: 'MiscColor1' },
];
